[project]
name = "minecraft-sync"
version = "0.1.1"
description = "Simple project to automate setting up minecraft mods for my friends"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "requests>=2.32.3",
]
